### ISSUE TITLE
Parágrafo do "Antes de Começar"

### ISSUE THREAD

**Issue by carpitalisz** [ossu/computer-science-br#2]
Foi inserido um parágrafo inteiro em inglês [aqui](https://github.com/ossu/computer-science-br#antes-de-come%C3%A7ar) sem ter terminado o anterior, que está em pt-br. 

![image](https://user-images.githubusercontent.com/52382802/182661478-12b6d23b-ff89-4fa2-98cf-17b37d97a26b.png)

**Comment by Camilotk** [comment]
Concertado! Foi algum bug que misturou o texto com nosso texto de apoio em inglês.
